language: node_js

node_js:
  "8"

services: docker

before_script:
  - make install ENV=ci

script:
  - make lint DOCKER=false
  - make build
  - make publish ENV=ci

after_script:
  - docker images
